### ISSUE TITLE
why -1

### ISSUE THREAD

**Issue by thylm** [adib0073/Time_Series_Anomaly_Detection#2]
hello, thank you for sharing. I use Approach 3 - By DBSCAN to do time serues anomaly detection. But I don't know why you choose labels = -1 is the outlier. Could you please explain it for me? Thank you a lot.

**Comment by adib0073** [comment]
yes, sure all outliers in DBSCAN module is marked as -1, other datapoints with consistent pattern are lablled with whole number values.
